AWSTemplateFormatVersion: '2010-09-09'

Resources:

  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir HTTP

      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro

      ImageId: ami-0c02fb55956c7d316

      SecurityGroups:
        - !Ref WebSecurityGroup

      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd

          cat > /var/www/html/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <title>Examen Final</title>
              <style>
                  body{
                      font-family: Arial;
                      text-align:center;
                      margin-top:100px;
                  }
              </style>
          </head>
          <body>

          <h1>YICETH YULIANA VELASQUEZ GOMEZ</h1>
          <h2>0192312</h2>

          <p>Examen Final Arquitectura de Computadores</p>

          <button onclick="saludo()">Click</button>

          <script>
          function saludo(){
              alert("Hola Profesor Wilder");
          }
          </script>

          </body>
          </html>
          EOF

Outputs:

  InstanceId:
    Value: !Ref WebServer
